version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./instance:/app/instance
    environment:
      - SECRET_KEY=your-secure-secret-key-here  # 生产环境请更换为随机字符串
      - PROXY_HOST=http://flaresolverr:8191
      - TZ=Asia/Shanghai
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: always
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Shanghai
    ports:
      - "8191:8191"
    volumes:
      - ./flaresolverr:/app/flaresolverr
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8191"]
      interval: 30s
      timeout: 10s
      retries: 3

# 数据卷配置
volumes:
  data:
  instance:
  flaresolverr:
    