version: '3'

services:
  app:
    build: .
    container_name: vps-stock-monitor
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///data/database.db
    depends_on:
      - flaresolverr
    restart: always
    # 添加用户和组的映射，确保容器内的进程有足够的权限访问挂载的卷
    user: "1000:1000"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=none
    restart: always