services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PROXY_HOST=${PROXY_HOST:-http://flaresolverr:8191}
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./instance:/app/instance
    depends_on:
      - flaresolverr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/public/stocks"]
      interval: 30s
      timeout: 10s
      retries: 3

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: always
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
